linters-settings:
  maligned:
    suggest-new: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: cmd/updater/main.go
      text: "mnd: Magic number: 4, in <argument> detected"
      linters:
        - gomnd
    - path: cmd/updater/main.go
      text: "mnd: Magic number: 2, in <argument> detected"
      linters:
        - gomnd
    - path: _test\.go
      linters:
        - dupl

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    # - goerr113 # TODO
    - importas
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - exportloopref
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

run:
  skip-dirs:
    - .devcontainer
    - .github
